name: bavatar
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  equatable: ^2.0.1
  google_fonts: ^2.1.0
  gap: ^2.0.0
  flutter_bloc: ^7.0.1
  json_annotation: ^4.0.1
  bavatar_repository:
   path: packages/bavatar_repository
  intl: ^0.17.0
  cached_network_image: ^3.1.0-alpha.1
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.1.0
  very_good_analysis: ^2.1.0
  build_runner: ^2.0.5
  json_serializable: ^4.1.3

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/noise_bg.jpeg