name: bavatar_repository
description: A Dart Repository which manages the bavatar domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.0.1
  bavatar_api:
    path: ../bavatar_api

dev_dependencies:
  coverage: ^1.0.3
  mocktail: ^0.1.4
  build_runner: ^2.0.5
  json_serializable: ^4.1.3
  test: ^1.17.9