name: bavatar_api
description: A Dart API Client for the Bavatar API.
version: 1.0.1
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  json_annotation: ^4.0.1

dev_dependencies:
  mocktail: ^0.1.4
  build_runner: ^2.0.5
  json_serializable: ^4.1.3
  test: ^1.17.9